League.create!(name: "BMFFL")

Season.create!(year: 2011, league_id: 1, completed?: true)
Season.create!(year: 2012, league_id: 1, completed?: true)
Season.create!(year: 2013, league_id: 1, completed?: true)
Season.create!(year: 2014, league_id: 1, completed?: true)
Season.create!(year: 2015, league_id: 1, completed?: true)
Season.create!(year: 2016, league_id: 1, completed?: true)

Owner.create!(first_name: "Brian", last_name: "D")
Owner.create!(first_name: "Nick", last_name: "D")
Owner.create!(first_name: "Brian", last_name: "K")
Owner.create!(first_name: "Brad", last_name: "L")
Owner.create!(first_name: "Matt", last_name: "M")
Owner.create!(first_name: "Drew", last_name: "M")
Owner.create!(first_name: "Dan", last_name: "O")
Owner.create!(first_name: "Kyle", last_name: "P")
Owner.create!(first_name: "Sean", last_name: "S")
Owner.create!(first_name: "Isaac", last_name: "S")
Owner.create!(first_name: "Ryan", last_name: "D")

Team.create!(season_id: 1, name: "Iowa HerkysHeroes47"
Team.create!(season_id: 1, name: "Westside Whales"
Team.create!(season_id: 1, name: "Bustin McNutts"
Team.create!(season_id: 1, name: "The Ricky Stanzis"
Team.create!(season_id: 1, name: "Iowa Football"
Team.create!(season_id: 1, name: "Orange Crush"
Team.create!(season_id: 1, name: "Balls Tech"
Team.create!(season_id: 1, name: "The Green Bay Belts"
Team.create!(season_id: 1, name: "Dirty Birds"
Team.create!(season_id: 1, name: "The Belt"
Team.create!(season_id: 2, name: "Iowa HerkysHeroes47"
Team.create!(season_id: 2, name: "Westside Whales"
Team.create!(season_id: 2, name: "Dont Diss My Fiedorowicz"
Team.create!(season_id: 2, name: "The Ricky Stanzis"
Team.create!(season_id: 2, name: "Iowa Football"
Team.create!(season_id: 2, name: "Orange Crush"
Team.create!(season_id: 2, name: "Balls Tech"
Team.create!(season_id: 2, name: "The Green Bay Belts"
Team.create!(season_id: 2, name: "Dirty Birds"
Team.create!(season_id: 2, name: "Super Cam"
Team.create!(season_id: 3, name: "Iowa HerkysHeroes47"
Team.create!(season_id: 3, name: "Westside Whales"
Team.create!(season_id: 3, name: "Kaeptains of Fortetude"
Team.create!(season_id: 3, name: "The Ricky Stanzis"
Team.create!(season_id: 3, name: "Iowa Football"
Team.create!(season_id: 3, name: "Orange Crush"
Team.create!(season_id: 3, name: "Ballz Tech"
Team.create!(season_id: 3, name: "The Green Bay Belts"
Team.create!(season_id: 3, name: "Dirty Birds"
Team.create!(season_id: 3, name: "Mustache Madness"
Team.create!(season_id: 4, name: "Iowa HerkysHeroes47"
Team.create!(season_id: 4, name: "Westside Whales"
Team.create!(season_id: 4, name: "Harbaughs Dad Pants"
Team.create!(season_id: 4, name: "The Ricky Stanzis"
Team.create!(season_id: 4, name: "Iowa Football"
Team.create!(season_id: 4, name: "Orange Crush"
Team.create!(season_id: 4, name: "Ballz Tech"
Team.create!(season_id: 4, name: "The Green Bay Belts"
Team.create!(season_id: 4, name: "Dirty Birds"
Team.create!(season_id: 4, name: "Mustache Madness"
Team.create!(season_id: 5, name: "Iowa HerkysHeroes47"
Team.create!(season_id: 5, name: "Westside Whales"
Team.create!(season_id: 5, name: "Play Ack-Shun Rollout"
Team.create!(season_id: 5, name: "The Ricky Stanzis"
Team.create!(season_id: 5, name: "Iowa Football"
Team.create!(season_id: 5, name: "Orange Crush"
Team.create!(season_id: 5, name: "Ballz Tech"
Team.create!(season_id: 5, name: "Mr. Rodgers Neighborhood"
Team.create!(season_id: 5, name: "Mustache Madness"
Team.create!(season_id: 5, name: "Team R.F.W.F.G.B."
Team.create!(season_id: 6, name: "Iowa HerkysHeroes47"
Team.create!(season_id: 6, name: "Westside Whales"
Team.create!(season_id: 6, name: "Live Free and Beathard"
Team.create!(season_id: 6, name: "The Ricky Stanzis"
Team.create!(season_id: 6, name: "Iowa Football"
Team.create!(season_id: 6, name: "Orange Crush"
Team.create!(season_id: 6, name: "Ballz Tech"
Team.create!(season_id: 6, name: "Mr. Rodgers Neighborhood"
Team.create!(season_id: 6, name: "Mustache Madness"
Team.create!(season_id: 6, name: "Team R.F.W.F.G.B."

Game.create!(season_id: 1, week: 1, away_team_id: 4, away_score: 100, home_team_id: 2, home_score: 106.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 1, away_team_id: 6, away_score: 66, home_team_id: 10, home_score: 77.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 1, away_team_id: 3, away_score: 69.5, home_team_id: 9, home_score: 76.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 1, away_team_id: 7, away_score: 103.5, home_team_id: 1, home_score: 115.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 1, away_team_id: 8, away_score: 108.5, home_team_id: 5, home_score: 83.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 2, away_team_id: 6, away_score: 131, home_team_id: 4, home_score: 83, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 2, away_team_id: 7, away_score: 83.5, home_team_id: 3, home_score: 107.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 2, away_team_id: 10, away_score: 84.5, home_team_id: 8, home_score: 134, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 2, away_team_id: 9, away_score: 63.5, home_team_id: 5, home_score: 96.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 2, away_team_id: 1, away_score: 108, home_team_id: 2, home_score: 126.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 3, away_team_id: 4, away_score: 92, home_team_id: 8, home_score: 90.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 3, away_team_id: 5, away_score: 95, home_team_id: 3, home_score: 47.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 3, away_team_id: 2, away_score: 97.5, home_team_id: 7, home_score: 85.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 3, away_team_id: 9, away_score: 101.5, home_team_id: 10, home_score: 77.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 3, away_team_id: 1, away_score: 130, home_team_id: 6, home_score: 45.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 4, away_team_id: 4, away_score: 101, home_team_id: 1, home_score: 78.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 4, away_team_id: 2, away_score: 90, home_team_id: 5, home_score: 67, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 4, away_team_id: 8, away_score: 127.5, home_team_id: 9, home_score: 91.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 4, away_team_id: 3, away_score: 94.5, home_team_id: 10, home_score: 120, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 4, away_team_id: 7, away_score: 70.5, home_team_id: 6, home_score: 109, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 5, away_team_id: 7, away_score: 77, home_team_id: 4, home_score: 84, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 5, away_team_id: 1, away_score: 93.5, home_team_id: 9, home_score: 103.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 5, away_team_id: 10, away_score: 110.5, home_team_id: 5, home_score: 66, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 5, away_team_id: 6, away_score: 81, home_team_id: 2, home_score: 110.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 5, away_team_id: 3, away_score: 77.5, home_team_id: 8, home_score: 95, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 6, away_team_id: 5, away_score: 69.5, home_team_id: 4, home_score: 102.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 6, away_team_id: 3, away_score: 58, home_team_id: 6, home_score: 104.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 6, away_team_id: 8, away_score: 106, home_team_id: 7, home_score: 45, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 6, away_team_id: 9, away_score: 62.5, home_team_id: 2, home_score: 89, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 6, away_team_id: 10, away_score: 50, home_team_id: 1, home_score: 81.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 7, away_team_id: 4, away_score: 79, home_team_id: 9, home_score: 129.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 7, away_team_id: 6, away_score: 37, home_team_id: 8, home_score: 87, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 7, away_team_id: 7, away_score: 27.5, home_team_id: 5, home_score: 79.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 7, away_team_id: 2, away_score: 80.5, home_team_id: 10, home_score: 93.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 7, away_team_id: 1, away_score: 90.5, home_team_id: 3, home_score: 72.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 8, away_team_id: 10, away_score: 67.5, home_team_id: 4, home_score: 89, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 8, away_team_id: 5, away_score: 100, home_team_id: 6, home_score: 115.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 8, away_team_id: 9, away_score: 81, home_team_id: 7, home_score: 44.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 8, away_team_id: 3, away_score: 60.5, home_team_id: 2, home_score: 66.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 8, away_team_id: 8, away_score: 100, home_team_id: 1, home_score: 62, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 9, away_team_id: 2, away_score: 69, home_team_id: 4, home_score: 65, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 9, away_team_id: 6, away_score: 52, home_team_id: 9, home_score: 92, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 9, away_team_id: 5, away_score: 74, home_team_id: 10, home_score: 80, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 9, away_team_id: 1, away_score: 118.5, home_team_id: 7, home_score: 42, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 9, away_team_id: 8, away_score: 101.5, home_team_id: 3, home_score: 113, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 10, away_team_id: 4, away_score: 95, home_team_id: 6, home_score: 37, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 10, away_team_id: 7, away_score: 69, home_team_id: 10, home_score: 102.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 10, away_team_id: 9, away_score: 92, home_team_id: 3, home_score: 70.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 10, away_team_id: 5, away_score: 85, home_team_id: 8, home_score: 109.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 10, away_team_id: 2, away_score: 79.5, home_team_id: 1, home_score: 103, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 11, away_team_id: 4, away_score: 93, home_team_id: 3, home_score: 61.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 11, away_team_id: 8, away_score: 96, home_team_id: 10, home_score: 90, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 11, away_team_id: 7, away_score: 81, home_team_id: 2, home_score: 78, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 11, away_team_id: 5, away_score: 73, home_team_id: 9, home_score: 45.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 11, away_team_id: 6, away_score: 94.5, home_team_id: 1, home_score: 91.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 12, away_team_id: 1, away_score: 95.5, home_team_id: 4, home_score: 49, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 12, away_team_id: 2, away_score: 97, home_team_id: 8, home_score: 92, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 12, away_team_id: 3, away_score: 58.5, home_team_id: 5, home_score: 59, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 12, away_team_id: 10, away_score: 110.5, home_team_id: 9, home_score: 102, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 12, away_team_id: 6, away_score: 79, home_team_id: 7, home_score: 62, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 13, away_team_id: 4, away_score: 78, home_team_id: 7, home_score: 100, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 13, away_team_id: 1, away_score: 110.5, home_team_id: 5, home_score: 91, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 13, away_team_id: 9, away_score: 106, home_team_id: 8, home_score: 83, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 13, away_team_id: 2, away_score: 103.5, home_team_id: 6, home_score: 56.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 13, away_team_id: 10, away_score: 99, home_team_id: 3, home_score: 118, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 1, week: 14, away_team_id: 4, away_score: 110, home_team_id: 1, home_score: 104.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 1, week: 14, away_team_id: 10, away_score: 56.5, home_team_id: 8, home_score: 63, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 1, week: 14, away_team_id: 5, away_score: 91, home_team_id: 6, home_score: 101, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 14, away_team_id: 7, away_score: 99.5, home_team_id: 3, home_score: 113, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 15, away_team_id: 4, away_score: 80.5, home_team_id: 2, home_score: 88.5, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 1, week: 15, away_team_id: 8, away_score: 119.5, home_team_id: 9, home_score: 112.5, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 1, week: 15, away_team_id: 10, away_score: 67.5, home_team_id: 1, home_score: 62.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 15, away_team_id: 3, away_score: 85.5, home_team_id: 6, home_score: 103.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 15, away_team_id: 7, away_score: 38.5, home_team_id: 5, home_score: 87, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 16, away_team_id: 8, away_score: 99, home_team_id: 2, home_score: 86.5, completed?: true, game_type: "Super Bowl")
Game.create!(season_id: 1, week: 16, away_team_id: 4, away_score: 75, home_team_id: 9, home_score: 105, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 16, away_team_id: 10, away_score: 87.5, home_team_id: 1, home_score: 99.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 16, away_team_id: 5, away_score: 76, home_team_id: 6, home_score: 88, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 1, week: 16, away_team_id: 7, away_score: 67.5, home_team_id: 3, home_score: 50, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 1, away_team_id: 17, away_score: 66.5, home_team_id: 11, home_score: 113.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 1, away_team_id: 16, away_score: 99.5, home_team_id: 20, home_score: 75, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 1, away_team_id: 14, away_score: 71, home_team_id: 12, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 1, away_team_id: 18, away_score: 99.5, home_team_id: 15, home_score: 113, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 1, away_team_id: 13, away_score: 75.5, home_team_id: 19, home_score: 87, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 2, away_team_id: 11, away_score: 99.5, home_team_id: 12, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 2, away_team_id: 17, away_score: 95, home_team_id: 13, home_score: 33.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 2, away_team_id: 16, away_score: 125, home_team_id: 14, home_score: 92, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 2, away_team_id: 19, away_score: 139.5, home_team_id: 15, home_score: 59.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 2, away_team_id: 20, away_score: 104, home_team_id: 18, home_score: 52.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 3, away_team_id: 19, away_score: 86, home_team_id: 20, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 3, away_team_id: 15, away_score: 68.5, home_team_id: 13, home_score: 101, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 3, away_team_id: 11, away_score: 61.5, home_team_id: 16, home_score: 104.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 3, away_team_id: 12, away_score: 100, home_team_id: 17, home_score: 100, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 3, away_team_id: 14, away_score: 94, home_team_id: 18, home_score: 81.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 4, away_team_id: 14, away_score: 87.5, home_team_id: 11, home_score: 110.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 4, away_team_id: 13, away_score: 68.5, home_team_id: 20, home_score: 91.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 4, away_team_id: 12, away_score: 105.5, home_team_id: 15, home_score: 93, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 4, away_team_id: 17, away_score: 81, home_team_id: 16, home_score: 99.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 4, away_team_id: 18, away_score: 97, home_team_id: 19, home_score: 73, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 5, away_team_id: 16, away_score: 92.5, home_team_id: 12, home_score: 49, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 5, away_team_id: 17, away_score: 46.5, home_team_id: 14, home_score: 93, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 5, away_team_id: 20, away_score: 59.5, home_team_id: 15, home_score: 92, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 5, away_team_id: 13, away_score: 75, home_team_id: 18, home_score: 89, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 5, away_team_id: 11, away_score: 142, home_team_id: 19, home_score: 107, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 6, away_team_id: 20, away_score: 52, home_team_id: 11, home_score: 104.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 6, away_team_id: 19, away_score: 85.5, home_team_id: 12, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 6, away_team_id: 15, away_score: 107, home_team_id: 14, home_score: 111.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 6, away_team_id: 13, away_score: 69, home_team_id: 16, home_score: 84.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 6, away_team_id: 18, away_score: 83, home_team_id: 17, home_score: 62, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 7, away_team_id: 12, away_score: 62.5, home_team_id: 20, home_score: 94.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 7, away_team_id: 11, away_score: 100.5, home_team_id: 13, home_score: 61.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 7, away_team_id: 17, away_score: 68.5, home_team_id: 15, home_score: 97, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 7, away_team_id: 16, away_score: 89, home_team_id: 18, home_score: 77.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 7, away_team_id: 14, away_score: 80.5, home_team_id: 19, home_score: 61, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 8, away_team_id: 18, away_score: 100, home_team_id: 11, home_score: 65, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 8, away_team_id: 13, away_score: 60, home_team_id: 12, home_score: 73, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 8, away_team_id: 20, away_score: 96.5, home_team_id: 14, home_score: 70, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 8, away_team_id: 15, away_score: 98, home_team_id: 16, home_score: 88, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 8, away_team_id: 19, away_score: 44.5, home_team_id: 17, home_score: 98.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 9, away_team_id: 15, away_score: 131, home_team_id: 20, home_score: 71.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 9, away_team_id: 18, away_score: 110, home_team_id: 13, home_score: 81, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 9, away_team_id: 12, away_score: 76.5, home_team_id: 14, home_score: 141, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 9, away_team_id: 11, away_score: 73.5, home_team_id: 17, home_score: 104, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 9, away_team_id: 16, away_score: 90.5, home_team_id: 19, home_score: 58.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 10, away_team_id: 12, away_score: 84.5, home_team_id: 11, home_score: 94, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 10, away_team_id: 17, away_score: 85.5, home_team_id: 20, home_score: 48.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 10, away_team_id: 19, away_score: 88, home_team_id: 13, home_score: 53.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 10, away_team_id: 14, away_score: 107.5, home_team_id: 16, home_score: 120.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 10, away_team_id: 15, away_score: 77.5, home_team_id: 18, home_score: 56.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 11, away_team_id: 16, away_score: 84.5, home_team_id: 11, home_score: 68.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 11, away_team_id: 18, away_score: 79, home_team_id: 20, home_score: 110, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 11, away_team_id: 17, away_score: 45.5, home_team_id: 12, home_score: 78, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 11, away_team_id: 14, away_score: 72.5, home_team_id: 13, home_score: 50.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 11, away_team_id: 15, away_score: 64, home_team_id: 19, home_score: 69, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 12, away_team_id: 11, away_score: 65, home_team_id: 14, home_score: 99, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 12, away_team_id: 13, away_score: 82.5, home_team_id: 15, home_score: 94.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 12, away_team_id: 16, away_score: 82.5, home_team_id: 17, home_score: 60.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 12, away_team_id: 12, away_score: 70, home_team_id: 18, home_score: 97.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 12, away_team_id: 20, away_score: 94.5, home_team_id: 19, home_score: 125, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 13, away_team_id: 20, away_score: 86.5, home_team_id: 13, home_score: 83.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 13, away_team_id: 11, away_score: 55, home_team_id: 15, home_score: 114.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 13, away_team_id: 12, away_score: 89, home_team_id: 16, home_score: 87.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 13, away_team_id: 14, away_score: 71, home_team_id: 17, home_score: 95.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 13, away_team_id: 19, away_score: 92.5, home_team_id: 18, home_score: 74.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 2, week: 14, away_team_id: 13, away_score: 113, home_team_id: 12, home_score: 97, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 14, away_team_id: 11, away_score: 84, home_team_id: 15, home_score: 106, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 2, week: 14, away_team_id: 17, away_score: 128, home_team_id: 18, home_score: 67.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 14, away_team_id: 20, away_score: 75.5, home_team_id: 19, home_score: 97.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 2, week: 15, away_team_id: 20, away_score: 105, home_team_id: 11, home_score: 121, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 15, away_team_id: 19, away_score: 83.5, home_team_id: 14, home_score: 56, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 2, week: 15, away_team_id: 15, away_score: 96, home_team_id: 16, home_score: 58.5, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 2, week: 15, away_team_id: 13, away_score: 82, home_team_id: 17, home_score: 67.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 15, away_team_id: 12, away_score: 110.5, home_team_id: 18, home_score: 98, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 16, away_team_id: 20, away_score: 65, home_team_id: 11, home_score: 99.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 16, away_team_id: 13, away_score: 121.5, home_team_id: 12, home_score: 72.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 16, away_team_id: 14, away_score: 104.5, home_team_id: 16, home_score: 102, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 16, away_team_id: 17, away_score: 104, home_team_id: 18, home_score: 91, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 2, week: 16, away_team_id: 15, away_score: 80.5, home_team_id: 19, home_score: 117.5, completed?: true, game_type: "Super Bowl")
Game.create!(season_id: 3, week: 1, away_team_id: 27, away_score: 102.5, home_team_id: 21, home_score: 125, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 1, away_team_id: 26, away_score: 76.5, home_team_id: 30, home_score: 83, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 1, away_team_id: 24, away_score: 76, home_team_id: 22, home_score: 86.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 1, away_team_id: 28, away_score: 125.5, home_team_id: 25, home_score: 92.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 1, away_team_id: 23, away_score: 115, home_team_id: 29, home_score: 106, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 2, away_team_id: 21, away_score: 82, home_team_id: 22, home_score: 79, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 2, away_team_id: 27, away_score: 96.5, home_team_id: 23, home_score: 71.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 2, away_team_id: 26, away_score: 94.5, home_team_id: 24, home_score: 73, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 2, away_team_id: 29, away_score: 97, home_team_id: 25, home_score: 102.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 2, away_team_id: 30, away_score: 125, home_team_id: 28, home_score: 59, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 3, away_team_id: 29, away_score: 56.5, home_team_id: 30, home_score: 75, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 3, away_team_id: 25, away_score: 92.5, home_team_id: 23, home_score: 60, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 3, away_team_id: 21, away_score: 62.5, home_team_id: 26, home_score: 91, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 3, away_team_id: 22, away_score: 73, home_team_id: 27, home_score: 96, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 3, away_team_id: 24, away_score: 98, home_team_id: 28, home_score: 96.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 4, away_team_id: 24, away_score: 109, home_team_id: 21, home_score: 117, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 4, away_team_id: 23, away_score: 102, home_team_id: 30, home_score: 119, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 4, away_team_id: 22, away_score: 66, home_team_id: 25, home_score: 84.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 4, away_team_id: 27, away_score: 112, home_team_id: 26, home_score: 72, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 4, away_team_id: 28, away_score: 73.5, home_team_id: 29, home_score: 90, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 5, away_team_id: 26, away_score: 114.5, home_team_id: 22, home_score: 77, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 5, away_team_id: 27, away_score: 132, home_team_id: 24, home_score: 97.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 5, away_team_id: 30, away_score: 58, home_team_id: 25, home_score: 79.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 5, away_team_id: 23, away_score: 104, home_team_id: 28, home_score: 74.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 5, away_team_id: 21, away_score: 76, home_team_id: 29, home_score: 78.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 6, away_team_id: 30, away_score: 77, home_team_id: 21, home_score: 107.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 6, away_team_id: 29, away_score: 83.5, home_team_id: 22, home_score: 61.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 6, away_team_id: 25, away_score: 103.5, home_team_id: 24, home_score: 48.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 6, away_team_id: 23, away_score: 49, home_team_id: 26, home_score: 83.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 6, away_team_id: 28, away_score: 79, home_team_id: 27, home_score: 67, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 7, away_team_id: 22, away_score: 26, home_team_id: 30, home_score: 88.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 7, away_team_id: 21, away_score: 76.5, home_team_id: 23, home_score: 79, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 7, away_team_id: 27, away_score: 119.5, home_team_id: 25, home_score: 69.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 7, away_team_id: 26, away_score: 100.5, home_team_id: 28, home_score: 116.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 7, away_team_id: 24, away_score: 81, home_team_id: 29, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 8, away_team_id: 28, away_score: 94.5, home_team_id: 21, home_score: 104, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 8, away_team_id: 23, away_score: 101.5, home_team_id: 22, home_score: 53.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 8, away_team_id: 30, away_score: 115.5, home_team_id: 24, home_score: 94.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 8, away_team_id: 25, away_score: 102, home_team_id: 26, home_score: 64, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 8, away_team_id: 29, away_score: 70.5, home_team_id: 27, home_score: 72, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 9, away_team_id: 25, away_score: 115.5, home_team_id: 30, home_score: 80.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 9, away_team_id: 28, away_score: 82, home_team_id: 23, home_score: 129, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 9, away_team_id: 22, away_score: 66, home_team_id: 24, home_score: 96.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 9, away_team_id: 21, away_score: 92, home_team_id: 27, home_score: 80, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 9, away_team_id: 26, away_score: 89.5, home_team_id: 29, home_score: 137, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 10, away_team_id: 22, away_score: 61.5, home_team_id: 21, home_score: 84, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 10, away_team_id: 27, away_score: 72, home_team_id: 30, home_score: 78, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 10, away_team_id: 29, away_score: 99, home_team_id: 23, home_score: 51.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 10, away_team_id: 24, away_score: 80, home_team_id: 26, home_score: 105, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 10, away_team_id: 25, away_score: 101.5, home_team_id: 28, home_score: 76, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 11, away_team_id: 26, away_score: 104, home_team_id: 21, home_score: 80.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 11, away_team_id: 28, away_score: 92, home_team_id: 30, home_score: 105.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 11, away_team_id: 27, away_score: 53.5, home_team_id: 22, home_score: 66.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 11, away_team_id: 24, away_score: 71.5, home_team_id: 23, home_score: 104, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 11, away_team_id: 25, away_score: 89.5, home_team_id: 29, home_score: 57, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 12, away_team_id: 21, away_score: 76.5, home_team_id: 24, home_score: 54.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 12, away_team_id: 23, away_score: 125.5, home_team_id: 25, home_score: 54, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 12, away_team_id: 26, away_score: 52.5, home_team_id: 27, home_score: 71, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 12, away_team_id: 22, away_score: 67.5, home_team_id: 28, home_score: 103.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 12, away_team_id: 30, away_score: 65.5, home_team_id: 29, home_score: 87, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 13, away_team_id: 30, away_score: 99.5, home_team_id: 23, home_score: 136, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 13, away_team_id: 21, away_score: 91, home_team_id: 25, home_score: 78.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 13, away_team_id: 22, away_score: 73.5, home_team_id: 26, home_score: 73, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 13, away_team_id: 24, away_score: 97.5, home_team_id: 27, home_score: 128, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 13, away_team_id: 29, away_score: 87.5, home_team_id: 28, home_score: 62, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 3, week: 14, away_team_id: 27, away_score: 132.5, home_team_id: 30, home_score: 64.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 3, week: 14, away_team_id: 29, away_score: 96.5, home_team_id: 23, home_score: 142.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 3, week: 14, away_team_id: 22, away_score: 81.5, home_team_id: 24, home_score: 99, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 14, away_team_id: 28, away_score: 115, home_team_id: 26, home_score: 103, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 15, away_team_id: 27, away_score: 107, home_team_id: 21, home_score: 49, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 3, week: 15, away_team_id: 29, away_score: 123.5, home_team_id: 30, home_score: 79, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 15, away_team_id: 23, away_score: 103, home_team_id: 25, home_score: 95, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 3, week: 15, away_team_id: 22, away_score: 86, home_team_id: 26, home_score: 87.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 15, away_team_id: 24, away_score: 52.5, home_team_id: 28, home_score: 103, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 16, away_team_id: 25, away_score: 79, home_team_id: 21, home_score: 70, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 16, away_team_id: 29, away_score: 88.5, home_team_id: 30, home_score: 58.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 16, away_team_id: 27, away_score: 114, home_team_id: 23, home_score: 84, completed?: true, game_type: "Super Bowl")
Game.create!(season_id: 3, week: 16, away_team_id: 22, away_score: 76.5, home_team_id: 24, home_score: 58.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 3, week: 16, away_team_id: 28, away_score: 102, home_team_id: 26, home_score: 80, completed?: true, game_type: "Consolation Game")

Game.create!(season_id: 4, week: 1, away_team_id: 37, away_score: 68, home_team_id: 31, home_score: 85.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 1, away_team_id: 36, away_score: 96, home_team_id: 40, home_score: 103.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 1, away_team_id: 34, away_score: 77.5, home_team_id: 32, home_score: 101, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 1, away_team_id: 38, away_score: 66.5, home_team_id: 35, home_score: 66, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 1, away_team_id: 33, away_score: 78.5, home_team_id: 39, home_score: 106.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 2, away_team_id: 31, away_score: 92.5, home_team_id: 32, home_score: 75, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 2, away_team_id: 37, away_score: 47, home_team_id: 33, home_score: 41.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 2, away_team_id: 36, away_score: 100, home_team_id: 34, home_score: 116, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 2, away_team_id: 39, away_score: 72.5, home_team_id: 35, home_score: 85.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 2, away_team_id: 40, away_score: 92.5, home_team_id: 38, home_score: 117.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 3, away_team_id: 39, away_score: 78.5, home_team_id: 40, home_score: 85.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 3, away_team_id: 35, away_score: 63.5, home_team_id: 33, home_score: 58, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 3, away_team_id: 31, away_score: 96.5, home_team_id: 36, home_score: 86, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 3, away_team_id: 32, away_score: 90.5, home_team_id: 37, home_score: 70, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 3, away_team_id: 34, away_score: 76.5, home_team_id: 38, home_score: 52.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 4, away_team_id: 34, away_score: 130.5, home_team_id: 31, home_score: 81, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 4, away_team_id: 33, away_score: 74.5, home_team_id: 40, home_score: 131.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 4, away_team_id: 32, away_score: 96, home_team_id: 35, home_score: 74.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 4, away_team_id: 37, away_score: 85.5, home_team_id: 36, home_score: 90.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 4, away_team_id: 38, away_score: 62.5, home_team_id: 39, home_score: 61.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 5, away_team_id: 36, away_score: 120, home_team_id: 32, home_score: 96.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 5, away_team_id: 37, away_score: 72, home_team_id: 34, home_score: 82.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 5, away_team_id: 40, away_score: 67.5, home_team_id: 35, home_score: 76, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 5, away_team_id: 33, away_score: 95.5, home_team_id: 38, home_score: 70, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 5, away_team_id: 31, away_score: 57.5, home_team_id: 39, home_score: 72.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 6, away_team_id: 40, away_score: 79.5, home_team_id: 31, home_score: 109.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 6, away_team_id: 39, away_score: 111, home_team_id: 32, home_score: 94.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 6, away_team_id: 35, away_score: 44, home_team_id: 34, home_score: 90.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 6, away_team_id: 33, away_score: 92.5, home_team_id: 36, home_score: 116.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 6, away_team_id: 38, away_score: 104.5, home_team_id: 37, home_score: 79, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 7, away_team_id: 32, away_score: 92.5, home_team_id: 40, home_score: 85, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 7, away_team_id: 31, away_score: 57, home_team_id: 33, home_score: 68, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 7, away_team_id: 37, away_score: 75.5, home_team_id: 35, home_score: 63, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 7, away_team_id: 36, away_score: 96.5, home_team_id: 38, home_score: 80, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 7, away_team_id: 34, away_score: 70, home_team_id: 39, home_score: 78, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 8, away_team_id: 38, away_score: 97, home_team_id: 31, home_score: 141.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 8, away_team_id: 33, away_score: 58.5, home_team_id: 32, home_score: 104.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 8, away_team_id: 40, away_score: 122, home_team_id: 34, home_score: 98, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 8, away_team_id: 35, away_score: 116, home_team_id: 36, home_score: 140.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 8, away_team_id: 39, away_score: 81.5, home_team_id: 37, home_score: 56, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 9, away_team_id: 35, away_score: 98.5, home_team_id: 40, home_score: 73.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 9, away_team_id: 38, away_score: 109, home_team_id: 33, home_score: 45, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 9, away_team_id: 32, away_score: 119.5, home_team_id: 34, home_score: 89.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 9, away_team_id: 31, away_score: 119.5, home_team_id: 37, home_score: 65, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 9, away_team_id: 36, away_score: 54, home_team_id: 39, home_score: 79, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 10, away_team_id: 32, away_score: 116.5, home_team_id: 31, home_score: 72.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 10, away_team_id: 37, away_score: 54.5, home_team_id: 40, home_score: 85, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 10, away_team_id: 39, away_score: 84, home_team_id: 33, home_score: 109.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 10, away_team_id: 34, away_score: 106.5, home_team_id: 36, home_score: 109, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 10, away_team_id: 35, away_score: 74, home_team_id: 38, home_score: 91.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 11, away_team_id: 36, away_score: 70.5, home_team_id: 31, home_score: 38, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 11, away_team_id: 38, away_score: 90.5, home_team_id: 40, home_score: 75, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 11, away_team_id: 37, away_score: 79, home_team_id: 32, home_score: 77.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 11, away_team_id: 34, away_score: 85, home_team_id: 33, home_score: 105.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 11, away_team_id: 35, away_score: 121.5, home_team_id: 39, home_score: 72.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 12, away_team_id: 31, away_score: 51.5, home_team_id: 34, home_score: 102.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 12, away_team_id: 33, away_score: 139.5, home_team_id: 35, home_score: 124, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 12, away_team_id: 36, away_score: 92.5, home_team_id: 37, home_score: 65.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 12, away_team_id: 32, away_score: 70, home_team_id: 38, home_score: 104.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 12, away_team_id: 40, away_score: 71, home_team_id: 39, home_score: 104.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 13, away_team_id: 40, away_score: 110, home_team_id: 33, home_score: 61, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 13, away_team_id: 31, away_score: 79.5, home_team_id: 35, home_score: 86.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 13, away_team_id: 32, away_score: 125, home_team_id: 36, home_score: 70, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 13, away_team_id: 34, away_score: 114, home_team_id: 37, home_score: 104, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 13, away_team_id: 39, away_score: 112.5, home_team_id: 38, home_score: 77.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 4, week: 14, away_team_id: 37, away_score: 108, home_team_id: 33, home_score: 76, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 14, away_team_id: 31, away_score: 91, home_team_id: 35, home_score: 120.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 14, away_team_id: 40, away_score: 70, home_team_id: 36, home_score: 82.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 4, week: 14, away_team_id: 34, away_score: 94.5, home_team_id: 38, home_score: 73.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 4, week: 15, away_team_id: 33, away_score: 121, home_team_id: 31, home_score: 65.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 15, away_team_id: 36, away_score: 76, home_team_id: 32, home_score: 74.5, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 4, week: 15, away_team_id: 37, away_score: 88.5, home_team_id: 35, home_score: 81, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 15, away_team_id: 40, away_score: 69.5, home_team_id: 38, home_score: 88.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 15, away_team_id: 34, away_score: 71.5, home_team_id: 39, home_score: 58, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 4, week: 16, away_team_id: 37, away_score: 48.5, home_team_id: 33, home_score: 85.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 16, away_team_id: 31, away_score: 48.5, home_team_id: 35, home_score: 78.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 16, away_team_id: 34, away_score: 80, home_team_id: 36, home_score: 101.5, completed?: true, game_type: "Super Bowl")
Game.create!(season_id: 4, week: 16, away_team_id: 40, away_score: 82, home_team_id: 38, home_score: 91.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 4, week: 16, away_team_id: 32, away_score: 91, home_team_id: 39, home_score: 85.5, completed?: true, game_type: "Consolation Game")

Game.create!(season_id: 5, week: 1, away_team_id: 47, away_score: 82, home_team_id: 44, home_score: 108, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 1, away_team_id: 46, away_score: 53, home_team_id: 50, home_score: 103.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 1, away_team_id: 41, away_score: 117.5, home_team_id: 43, home_score: 77.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 1, away_team_id: 42, away_score: 74, home_team_id: 49, home_score: 109, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 1, away_team_id: 45, away_score: 77.5, home_team_id: 48, home_score: 101, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 2, away_team_id: 44, away_score: 65, home_team_id: 46, home_score: 90.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 2, away_team_id: 43, away_score: 69, home_team_id: 47, home_score: 97, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 2, away_team_id: 49, away_score: 81.5, home_team_id: 48, home_score: 71, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 2, away_team_id: 50, away_score: 46, home_team_id: 42, home_score: 69, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 2, away_team_id: 45, away_score: 88, home_team_id: 41, home_score: 77.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 3, away_team_id: 47, away_score: 130, home_team_id: 44, home_score: 76.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 3, away_team_id: 45, away_score: 138, home_team_id: 43, home_score: 107, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 3, away_team_id: 42, away_score: 81, home_team_id: 48, home_score: 72, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 3, away_team_id: 46, away_score: 67, home_team_id: 49, home_score: 144.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 3, away_team_id: 41, away_score: 117.5, home_team_id: 50, home_score: 100, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 4, away_team_id: 41, away_score: 69, home_team_id: 44, home_score: 60.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 4, away_team_id: 42, away_score: 61, home_team_id: 46, home_score: 55.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 4, away_team_id: 48, away_score: 60, home_team_id: 50, home_score: 106, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 4, away_team_id: 45, away_score: 86.5, home_team_id: 49, home_score: 80.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 4, away_team_id: 43, away_score: 79.5, home_team_id: 47, home_score: 57.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 5, away_team_id: 49, away_score: 101.5, home_team_id: 44, home_score: 75.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 5, away_team_id: 45, away_score: 88, home_team_id: 50, home_score: 137.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 5, away_team_id: 46, away_score: 92, home_team_id: 47, home_score: 53, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 5, away_team_id: 48, away_score: 70, home_team_id: 43, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 5, away_team_id: 42, away_score: 60, home_team_id: 41, home_score: 87, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 6, away_team_id: 50, away_score: 119.5, home_team_id: 44, home_score: 106.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 6, away_team_id: 41, away_score: 115, home_team_id: 47, home_score: 96, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 6, away_team_id: 48, away_score: 78.5, home_team_id: 46, home_score: 68, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 6, away_team_id: 45, away_score: 95.5, home_team_id: 42, home_score: 117.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 6, away_team_id: 49, away_score: 75.5, home_team_id: 43, home_score: 55.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 7, away_team_id: 41, away_score: 81.5, home_team_id: 44, home_score: 72.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 7, away_team_id: 45, away_score: 42.5, home_team_id: 46, home_score: 87.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 7, away_team_id: 42, away_score: 121, home_team_id: 47, home_score: 152, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 7, away_team_id: 43, away_score: 80.5, home_team_id: 50, home_score: 82, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 7, away_team_id: 48, away_score: 68, home_team_id: 49, home_score: 134.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 8, away_team_id: 42, away_score: 98.5, home_team_id: 44, home_score: 60.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 8, away_team_id: 45, away_score: 58, home_team_id: 48, home_score: 54.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 8, away_team_id: 41, away_score: 99, home_team_id: 47, home_score: 91, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 8, away_team_id: 50, away_score: 88, home_team_id: 43, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 8, away_team_id: 46, away_score: 87.5, home_team_id: 49, home_score: 105, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 9, away_team_id: 44, away_score: 78.5, home_team_id: 43, home_score: 98, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 9, away_team_id: 46, away_score: 93.5, home_team_id: 42, home_score: 79.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 9, away_team_id: 45, away_score: 96, home_team_id: 47, home_score: 123.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 9, away_team_id: 50, away_score: 123, home_team_id: 49, home_score: 94, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 9, away_team_id: 48, away_score: 89, home_team_id: 41, home_score: 115.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 10, away_team_id: 48, away_score: 61.5, home_team_id: 44, home_score: 97, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 10, away_team_id: 41, away_score: 102.5, home_team_id: 49, home_score: 112.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 10, away_team_id: 46, away_score: 22, home_team_id: 43, home_score: 112, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 10, away_team_id: 50, away_score: 52, home_team_id: 47, home_score: 117.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 10, away_team_id: 45, away_score: 39, home_team_id: 42, home_score: 60.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 11, away_team_id: 45, away_score: 100.5, home_team_id: 44, home_score: 54.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 11, away_team_id: 42, away_score: 61.5, home_team_id: 43, home_score: 65, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 11, away_team_id: 48, away_score: 41, home_team_id: 46, home_score: 68, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 11, away_team_id: 41, away_score: 85.5, home_team_id: 50, home_score: 106.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 11, away_team_id: 49, away_score: 88.5, home_team_id: 47, home_score: 85, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 12, away_team_id: 50, away_score: 79.5, home_team_id: 44, home_score: 81, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 12, away_team_id: 42, away_score: 136, home_team_id: 49, home_score: 72.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 12, away_team_id: 45, away_score: 70.5, home_team_id: 46, home_score: 84.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 12, away_team_id: 41, away_score: 90, home_team_id: 43, home_score: 121, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 12, away_team_id: 48, away_score: 62, home_team_id: 47, home_score: 70.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 13, away_team_id: 44, away_score: 51, home_team_id: 43, home_score: 112, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 13, away_team_id: 45, away_score: 111, home_team_id: 49, home_score: 100, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 13, away_team_id: 46, away_score: 90, home_team_id: 41, home_score: 116, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 13, away_team_id: 42, away_score: 77.5, home_team_id: 48, home_score: 55, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 13, away_team_id: 50, away_score: 142.5, home_team_id: 47, home_score: 105.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 5, week: 14, away_team_id: 48, away_score: 78.5, home_team_id: 44, home_score: 83, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 14, away_team_id: 46, away_score: 49.5, home_team_id: 43, home_score: 116.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 14, away_team_id: 47, away_score: 71, home_team_id: 42, home_score: 88, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 5, week: 14, away_team_id: 45, away_score: 46.5, home_team_id: 41, home_score: 87.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 5, week: 15, away_team_id: 45, away_score: 131, home_team_id: 47, home_score: 90.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 15, away_team_id: 42, away_score: 90, home_team_id: 50, home_score: 112.5, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 5, week: 15, away_team_id: 44, away_score: 75, home_team_id: 43, home_score: 110, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 15, away_team_id: 48, away_score: 117.5, home_team_id: 46, home_score: 79.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 15, away_team_id: 41, away_score: 70, home_team_id: 49, home_score: 82.5, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 5, week: 16, away_team_id: 42, away_score: 93.5, home_team_id: 41, home_score: 91, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 16, away_team_id: 45, away_score: 73, home_team_id: 47, home_score: 69.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 16, away_team_id: 49, away_score: 77, home_team_id: 50, home_score: 121, completed?: true, game_type: "Super Bowl")
Game.create!(season_id: 5, week: 16, away_team_id: 44, away_score: 105, home_team_id: 46, home_score: 74, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 5, week: 16, away_team_id: 48, away_score: 64, home_team_id: 43, home_score: 104.5, completed?: true, game_type: "Consolation Game")

Game.create!(season_id: 6, week: 1, away_team_id: 57, away_score: 68.5, home_team_id: 54, home_score: 80, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 1, away_team_id: 56, away_score: 64.5, home_team_id: 60, home_score: 99.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 1, away_team_id: 51, away_score: 91, home_team_id: 53, home_score: 116, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 1, away_team_id: 52, away_score: 79.5, home_team_id: 59, home_score: 111, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 1, away_team_id: 55, away_score: 131.5, home_team_id: 58, home_score: 106.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 2, away_team_id: 54, away_score: 83, home_team_id: 56, home_score: 76.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 2, away_team_id: 53, away_score: 72.5, home_team_id: 57, home_score: 84, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 2, away_team_id: 59, away_score: 59.5, home_team_id: 58, home_score: 81, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 2, away_team_id: 60, away_score: 96.5, home_team_id: 52, home_score: 56, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 2, away_team_id: 55, away_score: 107.5, home_team_id: 51, home_score: 103.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 3, away_team_id: 57, away_score: 142, home_team_id: 54, home_score: 104, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 3, away_team_id: 55, away_score: 33, home_team_id: 53, home_score: 105, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 3, away_team_id: 52, away_score: 64, home_team_id: 58, home_score: 99.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 3, away_team_id: 56, away_score: 81, home_team_id: 59, home_score: 87, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 3, away_team_id: 51, away_score: 105, home_team_id: 60, home_score: 83, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 4, away_team_id: 51, away_score: 86, home_team_id: 54, home_score: 116.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 4, away_team_id: 52, away_score: 62.5, home_team_id: 56, home_score: 37.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 4, away_team_id: 58, away_score: 89.5, home_team_id: 60, home_score: 118.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 4, away_team_id: 55, away_score: 79, home_team_id: 59, home_score: 99, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 4, away_team_id: 53, away_score: 73, home_team_id: 57, home_score: 97, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 5, away_team_id: 59, away_score: 124, home_team_id: 54, home_score: 140, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 5, away_team_id: 55, away_score: 71, home_team_id: 60, home_score: 76, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 5, away_team_id: 56, away_score: 72, home_team_id: 57, home_score: 114, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 5, away_team_id: 58, away_score: 69, home_team_id: 53, home_score: 100, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 5, away_team_id: 52, away_score: 83, home_team_id: 51, home_score: 103.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 6, away_team_id: 60, away_score: 75.5, home_team_id: 54, home_score: 67.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 6, away_team_id: 51, away_score: 62.5, home_team_id: 57, home_score: 60, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 6, away_team_id: 58, away_score: 137.5, home_team_id: 56, home_score: 74, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 6, away_team_id: 55, away_score: 51, home_team_id: 52, home_score: 46, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 6, away_team_id: 59, away_score: 97, home_team_id: 53, home_score: 91, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 7, away_team_id: 51, away_score: 96.5, home_team_id: 54, home_score: 119.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 7, away_team_id: 55, away_score: 82, home_team_id: 56, home_score: 99.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 7, away_team_id: 52, away_score: 113, home_team_id: 57, home_score: 63.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 7, away_team_id: 53, away_score: 98, home_team_id: 60, home_score: 103.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 7, away_team_id: 58, away_score: 60, home_team_id: 59, home_score: 57, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 8, away_team_id: 52, away_score: 75.5, home_team_id: 54, home_score: 91, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 8, away_team_id: 55, away_score: 100, home_team_id: 58, home_score: 81.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 8, away_team_id: 51, away_score: 97.5, home_team_id: 57, home_score: 55, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 8, away_team_id: 60, away_score: 76, home_team_id: 53, home_score: 100, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 8, away_team_id: 56, away_score: 79, home_team_id: 59, home_score: 108.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 9, away_team_id: 54, away_score: 105, home_team_id: 53, home_score: 90.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 9, away_team_id: 56, away_score: 36, home_team_id: 52, home_score: 79, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 9, away_team_id: 55, away_score: 67.5, home_team_id: 57, home_score: 80, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 9, away_team_id: 60, away_score: 161, home_team_id: 59, home_score: 76.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 9, away_team_id: 58, away_score: 85.5, home_team_id: 51, home_score: 79, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 10, away_team_id: 58, away_score: 97.5, home_team_id: 54, home_score: 82, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 10, away_team_id: 51, away_score: 90, home_team_id: 59, home_score: 44.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 10, away_team_id: 56, away_score: 64.5, home_team_id: 53, home_score: 93.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 10, away_team_id: 60, away_score: 94.5, home_team_id: 57, home_score: 100.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 10, away_team_id: 55, away_score: 113, home_team_id: 52, home_score: 93.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 11, away_team_id: 55, away_score: 105, home_team_id: 54, home_score: 85.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 11, away_team_id: 52, away_score: 63.5, home_team_id: 53, home_score: 97, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 11, away_team_id: 58, away_score: 68, home_team_id: 56, home_score: 58, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 11, away_team_id: 51, away_score: 94, home_team_id: 60, home_score: 90.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 11, away_team_id: 59, away_score: 110, home_team_id: 57, home_score: 69, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 12, away_team_id: 60, away_score: 87, home_team_id: 54, home_score: 116.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 12, away_team_id: 52, away_score: 60.5, home_team_id: 59, home_score: 59, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 12, away_team_id: 55, away_score: 97.5, home_team_id: 56, home_score: 52, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 12, away_team_id: 51, away_score: 105, home_team_id: 53, home_score: 53, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 12, away_team_id: 58, away_score: 127, home_team_id: 57, home_score: 107, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 13, away_team_id: 54, away_score: 100, home_team_id: 53, home_score: 105, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 13, away_team_id: 55, away_score: 97, home_team_id: 59, home_score: 76.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 13, away_team_id: 56, away_score: 87.5, home_team_id: 51, home_score: 97.5, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 13, away_team_id: 52, away_score: 89, home_team_id: 58, home_score: 69, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 13, away_team_id: 60, away_score: 87, home_team_id: 57, home_score: 92, completed?: true, game_type: "Regular Season")
Game.create!(season_id: 6, week: 14, away_team_id: 57, away_score: 94.5, home_team_id: 51, home_score: 95.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 6, week: 14, away_team_id: 60, away_score: 79.5, home_team_id: 58, home_score: 66.5, completed?: true, game_type: "Quarter Final")
Game.create!(season_id: 6, week: 14, away_team_id: 53, away_score: 57.5 home_team_id: 59, home_score: 55, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 14, away_team_id: 56, away_score: 40, home_team_id: 52, home_score: 67, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 15, away_team_id: 51, away_score: 70, home_team_id: 54, home_score: 100.5, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 6, week: 15, away_team_id: 60, away_score: 63.5, home_team_id: 55, home_score: 79, completed?: true, game_type: "Semi Final")
Game.create!(season_id: 6, week: 15, away_team_id: 57, away_score: 115.5, home_team_id: 58, home_score: 120, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 15, away_team_id: 52, away_score: 93, home_team_id: 53, home_score: 58.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 15, away_team_id: 56, away_score: 47, home_team_id: 59, home_score: 60, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 16, away_team_id: 55, away_score: 111.5, home_team_id: 54, home_score: 148, completed?: true, game_type: "Super Bowl")
Game.create!(season_id: 6, week: 16, away_team_id: 60, away_score: 65, home_team_id: 51, home_score: 127, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 16, away_team_id: 57, away_score: 76, home_team_id: 58, home_score: 91.5, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 16, away_team_id: 52, away_score: 104, home_team_id: 59, home_score: 48, completed?: true, game_type: "Consolation Game")
Game.create!(season_id: 6, week: 16, away_team_id: 56, away_score: 56, home_team_id: 53, home_score: 69, completed?: true, game_type: "Consolation Game")
